[project]
name = "unit-converter"
version = "1.0.2"
description = "Simple unit converter"
authors = [{ name = "Akxios" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.0",
    "jinja2>=3.1.6",
    "python-multipart>=0.0.21",
    "uvicorn[standard]>=0.40.0",
]